# Generated by Django 5.0.4 on 2024-04-30 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chat",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="message",
            name="uuid",
            field=models.UUIDField(
                auto_created=True, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
