# Generated by Django 5.0.4 on 2024-04-30 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_message_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
