# Generated by Django 5.0.4 on 2024-05-06 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_chat_options_alter_message_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.message",
            ),
        ),
    ]
